---
- name: Download Sinai Artifact
  shell: wget http://build-artifacts.library.ucla.edu/sinai-web/{{ secret_files[sinai_env]['github_branch'] }}/{{ secret_files[sinai_env]['sinai_vers'] }} -O /opt/sinai/{{ secret_files[sinai_env]['sinai_vers'] }}

- name: Set file attributes for Jar file
  file: path=/opt/sinai/{{ secret_files[sinai_env]['sinai_vers'] }} owner=sinai mode=0600 state=file

- name: Upload supervisord.conf
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf owner=root group=root mode=0600

- name: Upload sinai jceks
  copy: src=sinai-jceks dest={{ secret_files[sinai_env]['sinai_jceks'] }} owner=root group=root mode=0600
  no_log: true

- name: Bundle jceks with jar
  shell: jar -uf /opt/sinai/{{ secret_files[sinai_env]['sinai_vers'] }} -C /etc/sinai sinai.jceks

- name: Create Supervisor log file directory
  file: path=/var/log/supervisor mode=0700 state=directory

- name: Create Supervisor log file
  copy: content="" dest=/var/log/supervisor/supervisord.log mode=0600

- name: Make sure Supervisor is running
  shell: if [ ! -e /var/run/supervisor.sock ] ; then supervisord -c /etc/supervisord.conf ; fi

- name: Restart Supervisor with new config file
  supervisorctl: name=sinai state=restarted config=/etc/supervisord.conf